### ISSUE TITLE
FreeBSD - JSV8Engine.cpp compile errors

### ISSUE THREAD

**Issue by tymat** [ethereum/webthree-umbrella#115]
```
[  7%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/Common.cpp.o
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp: In function 'void dev::eth::reportException(v8::TryCatch*)':
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:54:14: error: 'v8::HandleScope::HandleScope()' is protected within this context
  HandleScope handle_scope;
              ^
In file included from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.h:27:0,
                 from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:26:
/usr/local/include/v8.h:816:13: note: declared protected here
   V8_INLINE HandleScope() {}
             ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp: At global scope:
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:97:26: error: 'Arguments' was not declared in this scope
 Handle<Value> consoleLog(Arguments const& _args)
                          ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:97:26: note: suggested alternative:
In file included from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.h:27:0,
                 from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:26:
/usr/local/include/v8.h:127:7: note:   'v8::internal::Arguments'
 class Arguments;
       ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:98:1: error: expected ',' or ';' before '{' token
 {
 ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:107:26: error: 'Arguments' was not declared in this scope
 Handle<Value> loadScript(Arguments const& _args)
                          ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:107:26: note: suggested alternative:
In file included from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.h:27:0,
                 from /home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:26:
/usr/local/include/v8.h:127:7: note:   'v8::internal::Arguments'
 class Arguments;
       ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:108:1: error: expected ',' or ';' before '{' token
 {
 ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:237:1: error: expected '}' at end of input
 }
 ^
/home/freebsd/projects/webthree-umbrella/webthree/libjsengine/JSV8Engine.cpp:237:1: error: expected '}' at end of input
webthree/libjsengine/CMakeFiles/jsengine.dir/build.make:119: recipe for target 'webthree/libjsengine/CMakeFiles/jsengine.dir/JSV8Engine.cpp.o' failed
gmake[2]: *** [webthree/libjsengine/CMakeFiles/jsengine.dir/JSV8Engine.cpp.o] Error 1
```

**Comment by bobsummerwill** [comment]
You can build V8 itself OK on FreeBSD, @tymat?

**Comment by MonsieurLanza** [comment]
Same here. Linux from scratch X64. 
V8 4.8 compiled successfully. V8 API change ? Which V8 version do you use ?

**Comment by MonsieurLanza** [comment]
Did some quick research. It is indeed caused by V8 API change :
https://docs.google.com/document/d/1g8JFi8T_oAE_7uAri7Njtig7fKaPDfotU6huOa1alds

hints :
https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/

libjsengine cannot compile with v8 v3.24+

**Comment by bobsummerwill** [comment]
So on OS X we're doing `brew install homebrew/versions/v8-315` which appears to be v 3.15.

Can you install a specific older version on FreeBSD, @tymat?

Thanks for the info, @MonsieurLanza.    What distro are you using?

**Comment by MonsieurLanza** [comment]
I'm using a custom built Linux system, based on http://linuxfromscratch.org/
The thing here is if you have, for some reason (wether it be LFS, FreeBSD or whatever) to get dependencies for web3 by yourself, you do not know which versions to pick until build fails and you dig in the deps' APIs.

**Comment by MonsieurLanza** [comment]
I confirm it compiles cleanly here with v8 3.15.

**Comment by bobsummerwill** [comment]
Thanks for that confirmation, @MonsieurLanza.

We need to do a better job with our external dependencies.   I don't believe that we have made any real effort at locking down version-ranges which we support.   That isn't an easy task when we have different packaging systems for each platform.

I have proposed that we pull at least some of our external dependencies into the webthree-umbrella as sub-modules, so that we can both lock-down on versioning and free ourselves from OS/distro-specific differences.

OS X is a rolling package system in Homebrew, which brings its own challenges.    And Windows is a total mess.

Anyway - glad you had success, @MonsieurLanza!

So @tymat - Do you have a means of building for FreeBSD versus V8 3.15?   I think that's your answer for the time being.

**Comment by MonsieurLanza** [comment]
Just found that list in webthree-helpers/extdep/getstuff.bat

```
call :download boost 1.55.0
call :download cryptopp 5.6.2
call :download curl 7.4.2
call :download jsoncpp 1.6.2
call :download json-rpc-cpp 0.5.0
call :download leveldb 1.2
call :download llvm 3.7.0
call :download microhttpd 0.9.2
call :download OpenCL_ICD 1
call :download qt 5.4.1
call :download miniupnpc 1.9
call :download v8 3.15.9
```

It would be really helpful to have it in the build doc somewhere.
(And i'm still not completely done : aleth won't build...)

**Comment by bobsummerwill** [comment]
Yes, and those are ONLY used for Windows builds.   They aren't canonical.

Please feel free to log a new ticket for your ongoing Aleth build issues, and we can worth through them together.

**Comment by chriseth** [comment]
We will remove V8 in the next release, please do not waste time on it. Please open new issues for other build problems.
