### ISSUE TITLE
build with boost 1.6 failed.  in ethash.cpp

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/webthree-umbrella#322]
when I build with boost 1.6 , failed by erros:

libethereum/libethashseal/Ethash.cpp:117:134: error: call of overloaded ‘error_info(boost::enable_if_c<true, boost::multiprecision::detail::expression<boost::multiprecision::detail::subtract_immediates, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<> >, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >, void, void> >::type)’ is ambiguous
       InvalidGasLimit() << errinfo_min( ((bigint )parentGasLimit - parentGasLimit / chainParams().u256Param("gasLimitBoundDivisor")) )

A simple fix is () the parameter of error_info.

**Comment by bobsummerwill** [comment]
Want to make a PR, @smartbitcoin?   Would be much appreciated!

**Comment by smartbitcoin** [comment]
maybe we just list boost 1.6 is not support currently,  b/c more build error in test case too, not worth patch it right now.

**Comment by bobsummerwill** [comment]
OK.   More generally, we are utterly lacking in discipline on versioning of external components.    My proposal is that we add most (all) of the external dependencies into the webthree-umbrella itself.   I will be doing that in the near future.
